openapi: 3.0.3
info:
  title: Github Repos API
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
tags:
  - name: Repository
paths:
  /users/{username}/repos:
    get:
      tags:
        - Repository
      summary: Get user's repos
      description: Gets extended data on all public repositories of a given user.
      operationId: getAllPublicRepos
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
            example: 'millefoglie'
      responses:
        200:
          description: Repositories list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoriesData'
        400:
          $ref: '#/x-responses/BadRequest'
        404:
          $ref: '#/x-responses/NotFound'
        406:
          $ref: '#/x-responses/NotAcceptable'
        500:
          $ref: '#/x-responses/InternalServerError'
components:
  schemas:
    ErrorResponse:
      description: |
        A generic error response.
      type: object
      properties:
        status:
          type: integer
          description: An HTTP status code.
          example: 500
        Message:
          type: string
          description: An error message.
          example: 'Internal Server Error'
      required:
        - status
        - Message
    RepositoriesData:
      description: |
        Extended repositories data containing a list of all public repositories of a user,
        their branches and last commit SHA in each of them.
      type: object
      properties:
        repos:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: A repository name.
              owner:
                type: string
                description: An owner's login.
              branches:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: A branch name.
                    lastCommitSha:
                      type: string
                      description: A last commit SHA.
x-responses:
  BadRequest:
    description: Validation exception or rule violation
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/ErrorResponse'
        example:
          status: 400
          Message: 'Bad Request'
  NotFound:
    description: Resource or reference not found
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/ErrorResponse'
        example:
          status: 404
          Message: 'Not Found'
  NotAcceptable:
    description: Resource or reference not found
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/ErrorResponse'
        example:
          status: 406
          Message: 'Not Acceptable'
  InternalServerError:
    description: Internal server error
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/ErrorResponse'
